services:
    q_fe.util.asymetric:
        class:      Querdos\QFileEncryptionBundle\Util\AsymetricUtil
        calls:
            - [ setKernel,          [ '@kernel' ]]
            - [ setQKeyManager,     [ '@qfe.manager.qkey']]
